<html>
<head>
<?php
require_once("components/head.html.php");
?>
</head>
<body>
<?php
require_once("components/header.html.php");
?>
<main>
<?php
require_once("components/recipeList.html.php");
require_once("components/recipeCreator.html.php");
?>
</main>
<footer>
<?php
require_once("components/footer.html.php");
?>
</footer>
</body>
</html>