<html>
<?php
require_once("components/head.html.php");
?>
<body>
<?php
require_once("components/header.html.php");
?>
<main>
<?php
require_once("components/profileInfoPanel.html.php");
?>
</main>
<?php
require_once("components/footer.html.php");
?>
</body>
</html>